[general]
# Smart pathing using placeholders
file = "{config.path}/PMS 3.1.xlsm"
vba_directory = "{config.path}/vba-files"
verbose = true
rubberduck_folders = true
in_file_headers = true
keep_open = true
encoding = "utf-8"
